- type: job
  id: Detective
  name: job-name-detective
  description: job-description-detective
  playTimeTracker: JobDetective
  requirements:
  - !type:DepartmentTimeRequirement
    department: Security
    time: 72000 # SS220-RoleTime
  startingGear: DetectiveGear
  icon: "JobIconDetective"
  supervisors: job-supervisors-hop
  canBeAntag: true
  access:
  - Brig
  - Maintenance
  - Service
  - Detective
  extendedAccess:
  - Security

- type: startingGear
  id: DetectiveGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitDetective
    outerClothing: ClothingOuterVestDetective
    back: ClothingBackpackSecurityFilledDetective
    shoes: ClothingShoesBootsCombatFilled
    eyes: ClothingEyesGlassesSecurity #ss-220-GlassesSecurity
    head: ClothingHeadHatFedoraBrown
    id: DetectivePDA
    ears: ClothingHeadsetSecurity
    belt: ClothingBeltHolsterFilled
  innerClothingSkirt: ClothingUniformJumpskirtDetective
  satchel: ClothingBackpackSatchelSecurityFilledDetective
  duffelbag: ClothingBackpackDuffelSecurityFilledDetective
